/// <reference path="dist/types/src/index.d.ts"/> 
// Reference is automatically generated by glup, use 'gulp init'
// ** Do not submit the above modifications **

/**
 * app should be main file, but there is an dir error in LiteLoaderBDS-nodejs
 */

import main from "./src/app";
// import Test from './test/Test';

mc.listen("onServerStarted", () => {
    // Test.preTest();
    main();
    // Test.postTest();
});
