const REVISION = '147dev';
module.exports.REVISION = REVISION
const MOUSE = { LEFT: 0, MIDDLE: 1, RIGHT: 2, ROTATE: 0, DOLLY: 1, PAN: 2 };
module.exports.MOUSE = MOUSE
const TOUCH = { ROTATE: 0, PAN: 1, DOLLY_PAN: 2, DOLLY_ROTATE: 3 };
module.exports.TOUCH = TOUCH
const CullFaceNone = 0;
module.exports.CullFaceNone = CullFaceNone
const CullFaceBack = 1;
module.exports.CullFaceBack = CullFaceBack
const CullFaceFront = 2;
module.exports.CullFaceFront = CullFaceFront
const CullFaceFrontBack = 3;
module.exports.CullFaceFrontBack = CullFaceFrontBack
const BasicShadowMap = 0;
module.exports.BasicShadowMap = BasicShadowMap
const PCFShadowMap = 1;
module.exports.PCFShadowMap = PCFShadowMap
const PCFSoftShadowMap = 2;
module.exports.PCFSoftShadowMap = PCFSoftShadowMap
const VSMShadowMap = 3;
module.exports.VSMShadowMap = VSMShadowMap
const FrontSide = 0;
module.exports.FrontSide = FrontSide
const BackSide = 1;
module.exports.BackSide = BackSide
const DoubleSide = 2;
module.exports.DoubleSide = DoubleSide
const NoBlending = 0;
module.exports.NoBlending = NoBlending
const NormalBlending = 1;
module.exports.NormalBlending = NormalBlending
const AdditiveBlending = 2;
module.exports.AdditiveBlending = AdditiveBlending
const SubtractiveBlending = 3;
module.exports.SubtractiveBlending = SubtractiveBlending
const MultiplyBlending = 4;
module.exports.MultiplyBlending = MultiplyBlending
const CustomBlending = 5;
module.exports.CustomBlending = CustomBlending
const AddEquation = 100;
module.exports.AddEquation = AddEquation
const SubtractEquation = 101;
module.exports.SubtractEquation = SubtractEquation
const ReverseSubtractEquation = 102;
module.exports.ReverseSubtractEquation = ReverseSubtractEquation
const MinEquation = 103;
module.exports.MinEquation = MinEquation
const MaxEquation = 104;
module.exports.MaxEquation = MaxEquation
const ZeroFactor = 200;
module.exports.ZeroFactor = ZeroFactor
const OneFactor = 201;
module.exports.OneFactor = OneFactor
const SrcColorFactor = 202;
module.exports.SrcColorFactor = SrcColorFactor
const OneMinusSrcColorFactor = 203;
module.exports.OneMinusSrcColorFactor = OneMinusSrcColorFactor
const SrcAlphaFactor = 204;
module.exports.SrcAlphaFactor = SrcAlphaFactor
const OneMinusSrcAlphaFactor = 205;
module.exports.OneMinusSrcAlphaFactor = OneMinusSrcAlphaFactor
const DstAlphaFactor = 206;
module.exports.DstAlphaFactor = DstAlphaFactor
const OneMinusDstAlphaFactor = 207;
module.exports.OneMinusDstAlphaFactor = OneMinusDstAlphaFactor
const DstColorFactor = 208;
module.exports.DstColorFactor = DstColorFactor
const OneMinusDstColorFactor = 209;
module.exports.OneMinusDstColorFactor = OneMinusDstColorFactor
const SrcAlphaSaturateFactor = 210;
module.exports.SrcAlphaSaturateFactor = SrcAlphaSaturateFactor
const NeverDepth = 0;
module.exports.NeverDepth = NeverDepth
const AlwaysDepth = 1;
module.exports.AlwaysDepth = AlwaysDepth
const LessDepth = 2;
module.exports.LessDepth = LessDepth
const LessEqualDepth = 3;
module.exports.LessEqualDepth = LessEqualDepth
const EqualDepth = 4;
module.exports.EqualDepth = EqualDepth
const GreaterEqualDepth = 5;
module.exports.GreaterEqualDepth = GreaterEqualDepth
const GreaterDepth = 6;
module.exports.GreaterDepth = GreaterDepth
const NotEqualDepth = 7;
module.exports.NotEqualDepth = NotEqualDepth
const MultiplyOperation = 0;
module.exports.MultiplyOperation = MultiplyOperation
const MixOperation = 1;
module.exports.MixOperation = MixOperation
const AddOperation = 2;
module.exports.AddOperation = AddOperation
const NoToneMapping = 0;
module.exports.NoToneMapping = NoToneMapping
const LinearToneMapping = 1;
module.exports.LinearToneMapping = LinearToneMapping
const ReinhardToneMapping = 2;
module.exports.ReinhardToneMapping = ReinhardToneMapping
const CineonToneMapping = 3;
module.exports.CineonToneMapping = CineonToneMapping
const ACESFilmicToneMapping = 4;
module.exports.ACESFilmicToneMapping = ACESFilmicToneMapping
const CustomToneMapping = 5;
module.exports.CustomToneMapping = CustomToneMapping

const UVMapping = 300;
module.exports.UVMapping = UVMapping
const CubeReflectionMapping = 301;
module.exports.CubeReflectionMapping = CubeReflectionMapping
const CubeRefractionMapping = 302;
module.exports.CubeRefractionMapping = CubeRefractionMapping
const EquirectangularReflectionMapping = 303;
module.exports.EquirectangularReflectionMapping = EquirectangularReflectionMapping
const EquirectangularRefractionMapping = 304;
module.exports.EquirectangularRefractionMapping = EquirectangularRefractionMapping
const CubeUVReflectionMapping = 306;
module.exports.CubeUVReflectionMapping = CubeUVReflectionMapping
const RepeatWrapping = 1000;
module.exports.RepeatWrapping = RepeatWrapping
const ClampToEdgeWrapping = 1001;
module.exports.ClampToEdgeWrapping = ClampToEdgeWrapping
const MirroredRepeatWrapping = 1002;
module.exports.MirroredRepeatWrapping = MirroredRepeatWrapping
const NearestFilter = 1003;
module.exports.NearestFilter = NearestFilter
const NearestMipmapNearestFilter = 1004;
module.exports.NearestMipmapNearestFilter = NearestMipmapNearestFilter
const NearestMipMapNearestFilter = 1004;
module.exports.NearestMipMapNearestFilter = NearestMipMapNearestFilter
const NearestMipmapLinearFilter = 1005;
module.exports.NearestMipmapLinearFilter = NearestMipmapLinearFilter
const NearestMipMapLinearFilter = 1005;
module.exports.NearestMipMapLinearFilter = NearestMipMapLinearFilter
const LinearFilter = 1006;
module.exports.LinearFilter = LinearFilter
const LinearMipmapNearestFilter = 1007;
module.exports.LinearMipmapNearestFilter = LinearMipmapNearestFilter
const LinearMipMapNearestFilter = 1007;
module.exports.LinearMipMapNearestFilter = LinearMipMapNearestFilter
const LinearMipmapLinearFilter = 1008;
module.exports.LinearMipmapLinearFilter = LinearMipmapLinearFilter
const LinearMipMapLinearFilter = 1008;
module.exports.LinearMipMapLinearFilter = LinearMipMapLinearFilter
const UnsignedByteType = 1009;
module.exports.UnsignedByteType = UnsignedByteType
const ByteType = 1010;
module.exports.ByteType = ByteType
const ShortType = 1011;
module.exports.ShortType = ShortType
const UnsignedShortType = 1012;
module.exports.UnsignedShortType = UnsignedShortType
const IntType = 1013;
module.exports.IntType = IntType
const UnsignedIntType = 1014;
module.exports.UnsignedIntType = UnsignedIntType
const FloatType = 1015;
module.exports.FloatType = FloatType
const HalfFloatType = 1016;
module.exports.HalfFloatType = HalfFloatType
const UnsignedShort4444Type = 1017;
module.exports.UnsignedShort4444Type = UnsignedShort4444Type
const UnsignedShort5551Type = 1018;
module.exports.UnsignedShort5551Type = UnsignedShort5551Type
const UnsignedInt248Type = 1020;
module.exports.UnsignedInt248Type = UnsignedInt248Type
const AlphaFormat = 1021;
module.exports.AlphaFormat = AlphaFormat
const RGBFormat = 1022;
module.exports.RGBFormat = RGBFormat // @deprecated since r137
const RGBAFormat = 1023;
module.exports.RGBAFormat = RGBAFormat
const LuminanceFormat = 1024;
module.exports.LuminanceFormat = LuminanceFormat
const LuminanceAlphaFormat = 1025;
module.exports.LuminanceAlphaFormat = LuminanceAlphaFormat
const DepthFormat = 1026;
module.exports.DepthFormat = DepthFormat
const DepthStencilFormat = 1027;
module.exports.DepthStencilFormat = DepthStencilFormat
const RedFormat = 1028;
module.exports.RedFormat = RedFormat
const RedIntegerFormat = 1029;
module.exports.RedIntegerFormat = RedIntegerFormat
const RGFormat = 1030;
module.exports.RGFormat = RGFormat
const RGIntegerFormat = 1031;
module.exports.RGIntegerFormat = RGIntegerFormat
const RGBAIntegerFormat = 1033;
module.exports.RGBAIntegerFormat = RGBAIntegerFormat

const RGB_S3TC_DXT1_Format = 33776;
module.exports.RGB_S3TC_DXT1_Format = RGB_S3TC_DXT1_Format
const RGBA_S3TC_DXT1_Format = 33777;
module.exports.RGBA_S3TC_DXT1_Format = RGBA_S3TC_DXT1_Format
const RGBA_S3TC_DXT3_Format = 33778;
module.exports.RGBA_S3TC_DXT3_Format = RGBA_S3TC_DXT3_Format
const RGBA_S3TC_DXT5_Format = 33779;
module.exports.RGBA_S3TC_DXT5_Format = RGBA_S3TC_DXT5_Format
const RGB_PVRTC_4BPPV1_Format = 35840;
module.exports.RGB_PVRTC_4BPPV1_Format = RGB_PVRTC_4BPPV1_Format
const RGB_PVRTC_2BPPV1_Format = 35841;
module.exports.RGB_PVRTC_2BPPV1_Format = RGB_PVRTC_2BPPV1_Format
const RGBA_PVRTC_4BPPV1_Format = 35842;
module.exports.RGBA_PVRTC_4BPPV1_Format = RGBA_PVRTC_4BPPV1_Format
const RGBA_PVRTC_2BPPV1_Format = 35843;
module.exports.RGBA_PVRTC_2BPPV1_Format = RGBA_PVRTC_2BPPV1_Format
const RGB_ETC1_Format = 36196;
module.exports.RGB_ETC1_Format = RGB_ETC1_Format
const RGB_ETC2_Format = 37492;
module.exports.RGB_ETC2_Format = RGB_ETC2_Format
const RGBA_ETC2_EAC_Format = 37496;
module.exports.RGBA_ETC2_EAC_Format = RGBA_ETC2_EAC_Format
const RGBA_ASTC_4x4_Format = 37808;
module.exports.RGBA_ASTC_4x4_Format = RGBA_ASTC_4x4_Format
const RGBA_ASTC_5x4_Format = 37809;
module.exports.RGBA_ASTC_5x4_Format = RGBA_ASTC_5x4_Format
const RGBA_ASTC_5x5_Format = 37810;
module.exports.RGBA_ASTC_5x5_Format = RGBA_ASTC_5x5_Format
const RGBA_ASTC_6x5_Format = 37811;
module.exports.RGBA_ASTC_6x5_Format = RGBA_ASTC_6x5_Format
const RGBA_ASTC_6x6_Format = 37812;
module.exports.RGBA_ASTC_6x6_Format = RGBA_ASTC_6x6_Format
const RGBA_ASTC_8x5_Format = 37813;
module.exports.RGBA_ASTC_8x5_Format = RGBA_ASTC_8x5_Format
const RGBA_ASTC_8x6_Format = 37814;
module.exports.RGBA_ASTC_8x6_Format = RGBA_ASTC_8x6_Format
const RGBA_ASTC_8x8_Format = 37815;
module.exports.RGBA_ASTC_8x8_Format = RGBA_ASTC_8x8_Format
const RGBA_ASTC_10x5_Format = 37816;
module.exports.RGBA_ASTC_10x5_Format = RGBA_ASTC_10x5_Format
const RGBA_ASTC_10x6_Format = 37817;
module.exports.RGBA_ASTC_10x6_Format = RGBA_ASTC_10x6_Format
const RGBA_ASTC_10x8_Format = 37818;
module.exports.RGBA_ASTC_10x8_Format = RGBA_ASTC_10x8_Format
const RGBA_ASTC_10x10_Format = 37819;
module.exports.RGBA_ASTC_10x10_Format = RGBA_ASTC_10x10_Format
const RGBA_ASTC_12x10_Format = 37820;
module.exports.RGBA_ASTC_12x10_Format = RGBA_ASTC_12x10_Format
const RGBA_ASTC_12x12_Format = 37821;
module.exports.RGBA_ASTC_12x12_Format = RGBA_ASTC_12x12_Format
const RGBA_BPTC_Format = 36492;
module.exports.RGBA_BPTC_Format = RGBA_BPTC_Format
const LoopOnce = 2200;
module.exports.LoopOnce = LoopOnce
const LoopRepeat = 2201;
module.exports.LoopRepeat = LoopRepeat
const LoopPingPong = 2202;
module.exports.LoopPingPong = LoopPingPong
const InterpolateDiscrete = 2300;
module.exports.InterpolateDiscrete = InterpolateDiscrete
const InterpolateLinear = 2301;
module.exports.InterpolateLinear = InterpolateLinear
const InterpolateSmooth = 2302;
module.exports.InterpolateSmooth = InterpolateSmooth
const ZeroCurvatureEnding = 2400;
module.exports.ZeroCurvatureEnding = ZeroCurvatureEnding
const ZeroSlopeEnding = 2401;
module.exports.ZeroSlopeEnding = ZeroSlopeEnding
const WrapAroundEnding = 2402;
module.exports.WrapAroundEnding = WrapAroundEnding
const NormalAnimationBlendMode = 2500;
module.exports.NormalAnimationBlendMode = NormalAnimationBlendMode
const AdditiveAnimationBlendMode = 2501;
module.exports.AdditiveAnimationBlendMode = AdditiveAnimationBlendMode
const TrianglesDrawMode = 0;
module.exports.TrianglesDrawMode = TrianglesDrawMode
const TriangleStripDrawMode = 1;
module.exports.TriangleStripDrawMode = TriangleStripDrawMode
const TriangleFanDrawMode = 2;
module.exports.TriangleFanDrawMode = TriangleFanDrawMode
const LinearEncoding = 3000;
module.exports.LinearEncoding = LinearEncoding
const sRGBEncoding = 3001;
module.exports.sRGBEncoding = sRGBEncoding
const BasicDepthPacking = 3200;
module.exports.BasicDepthPacking = BasicDepthPacking
const RGBADepthPacking = 3201;
module.exports.RGBADepthPacking = RGBADepthPacking
const TangentSpaceNormalMap = 0;
module.exports.TangentSpaceNormalMap = TangentSpaceNormalMap
const ObjectSpaceNormalMap = 1;
module.exports.ObjectSpaceNormalMap = ObjectSpaceNormalMap

// Color space string identifiers, matching CSS Color Module Level 4 and WebGPU names where available.
const NoColorSpace = '';
module.exports.NoColorSpace = NoColorSpace
const SRGBColorSpace = 'srgb';
module.exports.SRGBColorSpace = SRGBColorSpace
const LinearSRGBColorSpace = 'srgb-linear';
module.exports.LinearSRGBColorSpace = LinearSRGBColorSpace

const ZeroStencilOp = 0;
module.exports.ZeroStencilOp = ZeroStencilOp
const KeepStencilOp = 7680;
module.exports.KeepStencilOp = KeepStencilOp
const ReplaceStencilOp = 7681;
module.exports.ReplaceStencilOp = ReplaceStencilOp
const IncrementStencilOp = 7682;
module.exports.IncrementStencilOp = IncrementStencilOp
const DecrementStencilOp = 7683;
module.exports.DecrementStencilOp = DecrementStencilOp
const IncrementWrapStencilOp = 34055;
module.exports.IncrementWrapStencilOp = IncrementWrapStencilOp
const DecrementWrapStencilOp = 34056;
module.exports.DecrementWrapStencilOp = DecrementWrapStencilOp
const InvertStencilOp = 5386;
module.exports.InvertStencilOp = InvertStencilOp

const NeverStencilFunc = 512;
module.exports.NeverStencilFunc = NeverStencilFunc
const LessStencilFunc = 513;
module.exports.LessStencilFunc = LessStencilFunc
const EqualStencilFunc = 514;
module.exports.EqualStencilFunc = EqualStencilFunc
const LessEqualStencilFunc = 515;
module.exports.LessEqualStencilFunc = LessEqualStencilFunc
const GreaterStencilFunc = 516;
module.exports.GreaterStencilFunc = GreaterStencilFunc
const NotEqualStencilFunc = 517;
module.exports.NotEqualStencilFunc = NotEqualStencilFunc
const GreaterEqualStencilFunc = 518;
module.exports.GreaterEqualStencilFunc = GreaterEqualStencilFunc
const AlwaysStencilFunc = 519;
module.exports.AlwaysStencilFunc = AlwaysStencilFunc

const StaticDrawUsage = 35044;
module.exports.StaticDrawUsage = StaticDrawUsage
const DynamicDrawUsage = 35048;
module.exports.DynamicDrawUsage = DynamicDrawUsage
const StreamDrawUsage = 35040;
module.exports.StreamDrawUsage = StreamDrawUsage
const StaticReadUsage = 35045;
module.exports.StaticReadUsage = StaticReadUsage
const DynamicReadUsage = 35049;
module.exports.DynamicReadUsage = DynamicReadUsage
const StreamReadUsage = 35041;
module.exports.StreamReadUsage = StreamReadUsage
const StaticCopyUsage = 35046;
module.exports.StaticCopyUsage = StaticCopyUsage
const DynamicCopyUsage = 35050;
module.exports.DynamicCopyUsage = DynamicCopyUsage
const StreamCopyUsage = 35042;
module.exports.StreamCopyUsage = StreamCopyUsage

const GLSL1 = '100';
module.exports.GLSL1 = GLSL1
const GLSL3 = '300 es';
module.exports.GLSL3 = GLSL3

const _SRGBAFormat = 1035;
module.exports._SRGBAFormat = _SRGBAFormat // fallback for WebGL 1